import { StyleSheet } from "react-native";
import { colors } from "../../Theme/GlobalTheme";

const styles = StyleSheet.create({
    container:{
        flex:1,
        width:'100%',
        alignItems:'center',
        backgroundColor:colors.white,
    },
    optionContainer:{
        borderWidth:1,
        borderColor:colors.grey,
        borderRadius:6,
        flexDirection:'row',
        alignItems:'center',
        padding:5, 
        paddingLeft:'3%',
        paddingRight:'3%',
    },
    optionText:{
        color:colors.grey,
        fontSize:14,
        marginLeft:5,
        fontFamily:'Gilroy-SemiBold'
    },
    optionContainer2:{
        backgroundColor:colors.lightGreen,
        borderRadius:6,
        flexDirection:'row',
        alignItems:'center',
        padding:5,
        paddingLeft:'3%',
        paddingRight:'3%',
    },
    optionText2:{
        color:colors.white,
        fontSize:14,
        marginLeft:5,
        fontFamily:'Gilroy-SemiBold'
    },
    buttonContainer:{
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
        width:'80%',
        alignSelf:'flex-start',
        marginTop:'0%',
        marginBottom:"3%",
        marginLeft:'5%'
    },
    buttonSubContainer:{
        height:34,
        width:'48%',
        alignItems:'center',
        borderRadius:5,
        marginTop:'1%',
        justifyContent:'center'
    },
    buttonText:{
        fontSize:14,
        fontFamily:'Gilroy-SemiBold',
        color:colors.white,
    }
})
export default styles;